### ISSUE TITLE
No Docker on hub

### ISSUE THREAD

**Issue by Exist2Resist** [NoMore201/playmaker#10]
Unable to perform the pull from docker to my server.
There is no Dockerfile on the Docker hub. 
Can you upload it?

Thanks

**Comment by NoMore201** [comment]
Yes, I was just setting up build automation on dockerhub. It will be ready in a matter of minutes.

**Comment by NoMore201** [comment]
Building right now, it could take some time
https://hub.docker.com/r/nomore201/playmaker/builds/
