### ISSUE TITLE
Docker: playmaker has to be initialised after every recreation

### ISSUE THREAD

**Issue by HeaDBanGer84** [NoMore201/playmaker#12]
I use the docker image to host playmaker and every time i recreate the container (for example to use a newer image) playmaker has to be initialized again.
 I looked in your docker file and it seems, this is because you copied `playmaker.conf` in buildphase so that it would be overmounted when the container is started.

possible fix: write the file `/data/fdroid/playmaker.conf` during startup/initialization phase of the server

**Comment by NoMore201** [comment]
`playmaker.conf` is an old file, it's not used anymore by the application. I removed it in the dev branch.
To prevent security issues, playmaker store its data (such as credentials, authentication token ...) in program memory, so each time you start the container it will ask you this data again.
Another reason why I did this is because it is meant to be running for long time, so re-initializing shouldn't be a big problem. Let me know if you have a better approach.

**Comment by HeaDBanGer84** [comment]
I'm not sure how the API works, but perhaps its enough to store the auth_token and the mail address. storing password as plain text is not really a good solution. but entering password on every restart on a headless system neither.
Perhaps the API has also some crypted authentication method. Sorry for not having better idea. Its always the same problem. Security vs convenience. 😞

**Comment by HeaDBanGer84** [comment]
I'm not sure how the API works, but perhaps its enough to store the auth_token and the mail address. storing password as plain text is not really a good solution. but entering password on every restart on a headless system neither.
Perhaps the API has also some crypted authentication method. Sorry for not having better idea. Its always the same problem. Security vs convenience. :sad

**Comment by jcgruenhage** [comment]
Security is important, but this is pretty inconvenient. With an app password and proper file permissions, this should be secure enough.

**Comment by HeaDBanGer84** [comment]
Any news on this issue? Perhaps it is possible to...
- type in username & password
- create an API key and save it
- After getting the key delete username and password

Advantages:
- Key can bey revoked from google.
- Password cannot be corruped

Unfortunately I'm not 100% sure if it is technical possible.

**Comment by jcgruenhage** [comment]
Basically with an App Password we have the same situation, as for revocation and stuff like that, and people with 2FA need to use app passwords anyway.

Maybe the container could check if the password was in an environment variable, if it is, then this is taken for initialization, if not the user has to enter it. With that, the user can choose for themselves whether they need more security.

**Comment by jcgruenhage** [comment]
-> just store them damned password in some file and lock it via permissions.

**Comment by jcgruenhage** [comment]
Or have it read from an env var or docker secret or something like that

**Comment by NoMore201** [comment]
With commit c2083a0 in branch dev, you can supply credentials through env variables.
If you want to help testing, pull [latest dev build](https://hub.docker.com/r/nomore201/playmaker/builds/) as soon as it it ready.

Notice that during initialization server is unresponsive, so you should wait for the process to finish before you can see the homepage

**Comment by jcgruenhage** [comment]
I'll test asap, thank you!

**Comment by jcgruenhage** [comment]
Works fine. The report in this comment earlier, stating that it didn't work, was due to me having an outdated app password stored in my password manager.

**Comment by jcgruenhage** [comment]
I've just rebuilt the image locally, from the last commit on the dev branch, that hasn't helped, so I doubt it's a problem with docker hub taking the wrong commit or anything. I have tried the above with and without quotation marks too.

**Comment by Yannik** [comment]
@NoMore201 I don't think this really is a great fix for this. This way, the email/password is exposed to everyone who can get a listing of the containers. Storing the auth key in the playmaker directory seems much more secure, as it can only be accessed by root or the container. Could you possible enable storing the auth data in the playmaker directory?

**Comment by NoMore201** [comment]
@Yannik you're right, that's why I put the flag *not recommended* in the README (on the branch dev). It is a temporary workaround, I'll change it in the future. Of course the recommended approach to provide credentials is through the login page

**Comment by Yannik** [comment]
@NoMore201 Providing credentials through the login page is totally fine, but it is not very usable if you need to enter them every time you update your docker container. Is there is a reason not to store them in the playmaker directory?

**Comment by NoMore201** [comment]
@Yannik it's ok to store them inside the directory, but users should change directory permissions so that it cannot be read from others (`chmod -R 700 /srv/playmaker`), otherwise anyone can read that file.

Also, If I'm not wrong, only users from the `docker` group can access docker containers information. So there's no way a third party can access environment variables of a running container. Correct me if I'm wrong.

So in the end both approaches are at the same level in my opinion

**Comment by Yannik** [comment]
@NoMore201 On my machine atleast, all config config/keypass files inside the playmaker directory have root:root ownership and `600` permissions on the host.
I can see scenarios where you'd like to output stats about the docker containers (or similar things to this), so the information is quite a bit more vulnerable when passed as env var IMO. There are more problems with the env var approach though: The gmail account data will be saved in the bash_history file. 
When listing your running containers (with full entrypoint command), even shoulder surfing would be possible...
I don't think this is a good idea at all.

**Comment by NoMore201** [comment]
You're right, I didn't thought about bash history. I'll change this and report back here

**Comment by Yannik** [comment]
Great, thank you :)

**Comment by jcgruenhage** [comment]
Actually this was fine, depending on how you started the container: If you have the setup stored in a docker-compose file and the docker socket only accessible to root, then this was fine, really. Not that I mind the config file, I like that too, just wanted to note that env vars aren't insecure if handled properly. A huge load of official docker containers have passwords as env vars.
