### ISSUE TITLE
Repository Name/URL

### ISSUE THREAD

**Issue by jcgruenhage** [NoMore201/playmaker#14]
Currently by default there are bad values for this, it would be nice if this was configurable with environment variables.

**Comment by jcgruenhage** [comment]
Workaround: Configure those values in fdroid/config.py and restart the container afterwards (and initialize it again because of #12).

**Comment by NoMore201** [comment]
As for the name, I already made some changes in this commit on the dev branch 6d10b68. 

For the URL displayed in the sidebar, the information is gathered from the Window.location object in the javascript code, so it depends on where you are accessing the server. If your are accessing it from inside your machine, you will see something like `http://127.0.0.1/fdroid`, if you access it from the outside, maybe behind a proxy configured with https and your domain, you will see `https://yourdomain/fdroid`.

**Comment by j5k** [comment]
The Port is missing in this URL

**Comment by NoMore201** [comment]
Fixed with commit a099cc7
