### ISSUE TITLE
Can't download new apps

### ISSUE THREAD

**Issue by ptrinc** [NoMore201/playmaker#19]
When I try to download an app, which I have never downloaded, I get an error message saying like:
"com.instagram.android can't be downloaded"
However, I can redownload apps which I have removed but i cant get any new.

Here are the logs:
Downloading com.instagram.android
'App not purchased'
Failed to download com.instagram.android

I think problems started when i tried to install com.mapswithme.maps.pro

**Comment by NoMore201** [comment]
I have other reports of a similar behaviour. Probably this happens due to commit a1c10dd.

For some reason, my google accounts want every app to be downloaded using the `delivery` API, while other accounts still follow previous behaviour shown in the commit diff.

Try to build the playmaker docker image making sure to checkout the commit d3a9535 (right before the problematic one) and see if you can download apps

**Comment by ptrinc** [comment]
I tried that, but I have still the same problem

**Comment by NoMore201** [comment]
Go to you google account settings, and delete any reference to playmaker (it should be listed as a OnePlus One device). Wait some time and restart playmaker, then tell me if the problem persist

**Comment by ptrinc** [comment]
tried that. I waited about half an hour. still the same. I also tried changing the directories and I still can only download apps i have already downloaded.

**Comment by NoMore201** [comment]
With version `0.6.2` and gpapi `0.4.2`, your problem should be fixed. Try latest build on docker hub or build it, then let me know

**Comment by ptrinc** [comment]
That fixed it. thank you very much. I really appreciate your work, its the only way to get automatic updates for my apps without root or playstore.

**Comment by MarieSaphira** [comment]
Hi, having this problem now. Using a docker image built from [fellek/playmaker](https://github.com/fellek/playmaker) after having issue #54 . Already tried deleting any reference to playmaker in my google account settings.

**Comment by Jonny007-MKD** [comment]
Hi @MarieSaphira, currently you have to buy the app first in the play store (play.google.com), even if it is free. Probably this can be fixed in code, but I don't know how.

**Comment by mikken** [comment]
When I login into Play website, it's said that Spotify (`com.spotify.music`) isn't compatible with any of my devices. I tried with `DEVICE_CODE="oneplus3"` and `DEVICE_CODE="walleye"`. Same for other apps.

**Comment by mikken** [comment]
I should also mention that it's found in Playmaker's search results but not in Play's search. Normally incompatible apps aren't shown.

**Comment by mikken** [comment]
Since Aptoide and Huawei's appstore currently have almost every app that Google Play has (except those that contain in-app purchases) with no region restrictions, I decided to switch to Aptoide instead of Playmaker.

Playmaker is poorly maintained these days and issues keep popping up.
