### ISSUE TITLE
Running docker container on RPI3

### ISSUE THREAD

**Issue by olliejm** [NoMore201/playmaker#23]
If I run the command listed in the readme on RPI3 (after creating https files and adjusting locale), all I get is an empty /srv/fdroid folder and nothing coming up if I go to the pi's ip :5000 or /fdroid or :5000/fdroid , both with https and http prefix, nothing. 

The pi is headless on the network so I have no way to check if somehow it is successfully running locally, but I doubt it as if I run docker port playmaker it lists no entries and as I say, the /srv/fdroid folder is empty and I can't seem to find any other playmaker files on there.

Any idea what might be going on or how I could troubleshoot this issue, look at logs or something?

**Comment by NoMore201** [comment]
First of all, did you run playmaker with fdroid support?
```
$ pm-server --fdroid --debug
```

Assuming you installed fdroidserver tool from raspbian repository, it requires the Android SDK to work. As I can see on the SDK page [1], there is no SDK package for the ARM architecture. Try running the fdroid server tool and check the output:

```
$ /usr/bin/fdroid init -v
```


[1] https://developer.android.com/studio/index.html

**Comment by olliejm** [comment]
I was under the impression that when using Docker, the Android SDK and other dependencies weren't needed? For example simply installing Docker then running the command from the readme works fine on my laptop, and I pretty much repeated the same steps on the Pi.

-------- Original Message --------

**Comment by lllusion3418** [comment]
For me, the packages in the debian repositories work as well. The [`android-sdk`](https://packages.debian.org/stretch/android-sdk) meta package is available for armel,armhf and even mips. I don't know which packages are actually necessary, I just installed all of them to be sure.

**Comment by 05nelsonm** [comment]
Little bit of a noob here... 

Are there any tutorials on how to get this running on a 3b+ (from raspian install to working)?
I've got one running Nextcloudpi, but was thinking about getting another and setting this up on it. Any suggestions/help would be greatly appreciated.

Sorry for posting like this w/o an actual issue, but I couldn't for the life of me find any forums for Playmaker, and nomore.ovh is returning 404 error.

**Comment by NoMore201** [comment]
Use the Dockerfile in the repo as a guide for the installation process. This does not mean you need to install docker on RPI3, just check out the steps in that file and try to reproduce them. Basically you need to

- Install dependencies (check [Dockerfile](https://github.com/NoMore201/playmaker/blob/f3828fdfd92ad1971802adfaa967b908d1ac9e2a/Dockerfile#L3-L20) )
- Install the Android SDK. There's a debian package as pointed out by @lllusion3418 )
- Clone playmaker repository
- Install it an run `pm-server`

**Comment by OdinGitDat** [comment]
I have the same problem as OP (on Ubuntu server). I'm new to docker so I just pulled the image and ran the container with the command in the readme. I don't know what I'm missing and the readme doesn't have troubleshooting information or even an install guide.

I am sure the container is running but Ubuntu doesn't recognize pm-server as a command.
