### ISSUE TITLE
ValueError: certfile "/srv/playmaker.crt" does not exist

### ISSUE THREAD

**Issue by zz0rk** [NoMore201/playmaker#24]
Generated crt and key file with:

sudo openssl req \
       -newkey rsa:2048 -nodes -keyout /srv/playmaker.key \
       -x509 -days 3650 -out /srv/playmaker.crt

Files were created at specified location and are not empty. Docker logs playmaker show:

ValueError: certfile "/srv/playmaker.crt" does not exist

When I do docker run without 

    -e HTTPS_CERTFILE="/srv/playmaker.crt" \
    -e HTTPS_KEYFILE="/srv/playmaker.key" \

Everything works and I can access playmaker at http://localhost:5000/#!/login

**Comment by NoMore201** [comment]
Did you create certs on your host system or in the docker container? Environment variables are defined for the container, not the host operating system, so `/srv/playmaker.crt` refers to the `srv` directory in the root of the container.

**Comment by zz0rk** [comment]
Ah... gotcha. That was confusing since playmaker actually created a fdroid directory in /srv. I did locate the srv directory for the container and got it working. Thanks for your help!
