### ISSUE TITLE
App runs as root

### ISSUE THREAD

**Issue by fernandocollova** [NoMore201/playmaker#26]
__What happens?__

When I run `ps -ely` inside the container, I get this:
> S   UID   PID  PPID  C PRI  NI   RSS      SZ      WCHAN  TTY       TIME       CMD
> S     0      1       0      0  80   0   748       1073      wait        ?        00:00:00     sh
> S     0      6       1      0  80   0 48940   236308       -          ?        00:00:08 python3
> S     0     40      0      0  80   0  3648      4989       wait       ?        00:00:00    bash
> R     0     49     40     0  80   0  1564      7486         -          ?        00:00:00     ps

__What should've happened?__

I shouldn't see python3 running as root

__How to reproduce?__

Create the app's container as stated in the repo, `run docker-compose exec playmeker /bin/bash` and inside the console run `ps -ely`

__Some meta?__

Not much, I just think running a web server as root is not cool. Also, I don't know why `sh` is in PID 1, as you seem to be setting the ENTRYPOINT correctly in your dockerfile.

And, also again, I don't know why github is removing the spcaes in the "What happens?" part. I tried to format it as nice as I could.

**Comment by NoMore201** [comment]
Solved with commit f3828fd. If you already have an fdroid directory on your host you need to chown it

    # chown -R 999:999 /path/to/fdroid
