### ISSUE TITLE
Freeze on Loading apps into cache, please wait

### ISSUE THREAD

**Issue by dizzy666** [NoMore201/playmaker#30]
After downloading (com.textra) and restart the container freeze on "Loading apps into cache, please wait".
Log shows no error.

**Comment by mikken** [comment]
I also get this freeze with clean /srv/fdroid (mount point) directory and latest playmaker 0.6.3.

**Comment by bakunin1848** [comment]
In my specific case I had an application that provoked that failure. It was google chrome I think remember. My advice: remove all the applications from the repository and go putting them from 5 to 5 and restart until you find the application that causes this failure. I would say that some application causes that situation. I hope I help you

**Comment by mikken** [comment]
No, this is a clean install, without any user data in container :(

**Comment by bakunin1848** [comment]
If you do not have much containers, I would recommend starting from 0.
Try to mount the container without https or reverse proxy in case you use it and in /tmp for example

1. docker stop $ (docker ps -a -q)
2. docker rm $ (docker ps -a -q)
3. docker system prune -a -f
4. docker run --name ="frepo" -d -p 5000:5000 -v /tmp:/data/fdroid nomore201/playmaker
5. Go to http://IP:5000

I hope it helps you.

**Comment by Findus23** [comment]
I am also having the same issue after having to restart the container. 
Removing and recreating the container after emptying the fdroid folder fixes the issue every time until I restart the container again.
But I think @jos1264 is right as I think this only started after I added Chrome. I'll try to leave out Chrome next time and will report back.

**Comment by jkothe** [comment]
I am also having the same issue with fresh and empty container and no other containers on local host.

```
# docker-compose up --force-recreate
Recreating store_playmaker_1 ... done
Attaching to store_playmaker_1
playmaker_1  | Repo already initalized, skipping init
playmaker_1  | Checking config.py file
playmaker_1  | Skipping fdroid update
playmaker_1  | WARNING:tornado.access:404 GET /favicon.ico (172.20.0.1) 1.22ms
playmaker_1  | ERROR:tornado.application:Uncaught exception POST /api/login (172.20.0.1)
playmaker_1  | HTTPServerRequest(protocol='http', host='localhost:5000', method='POST', uri='/api/login', version='HTTP/1.1', remote_ip='172.20.0.1', headers={'Host': 'localhost:5000', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0', 'Accept': 'application/json, text/plain, */*', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Referer': 'http://localhost:5000/', 'Content-Type': 'application/json;charset=utf-8', 'Content-Length': '54', 'Connection': 'keep-alive'})
playmaker_1  | Traceback (most recent call last):
playmaker_1  |   File "/usr/local/lib/python3.7/site-packages/tornado/web.py", line 1512, in _execute
playmaker_1  |     result = yield result
playmaker_1  |   File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 1055, in run
playmaker_1  |     value = future.result()
playmaker_1  |   File "/usr/local/lib/python3.7/site-packages/tornado/concurrent.py", line 238, in result
playmaker_1  |     raise_exc_info(self._exc_info)
playmaker_1  |   File "<string>", line 4, in raise_exc_info
playmaker_1  |   File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 1063, in run
playmaker_1  |     yielded = self.gen.throw(*exc_info)
playmaker_1  |   File "/usr/local/lib/python3.7/site-packages/playmaker/server.py", line 102, in post
playmaker_1  |     result = yield self.login()
playmaker_1  |   File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 1055, in run
playmaker_1  |     value = future.result()
playmaker_1  |   File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 425, in result
playmaker_1  |     return self.__get_result()
playmaker_1  |   File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
playmaker_1  |     raise self._exception
playmaker_1  |   File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
playmaker_1  |     result = self.fn(*self.args, **self.kwargs)
playmaker_1  |   File "/usr/local/lib/python3.7/site-packages/playmaker/server.py", line 45, in login
playmaker_1  |     return service.login()
playmaker_1  |   File "/usr/local/lib/python3.7/site-packages/playmaker/service.py", line 182, in login
playmaker_1  |     None, None)
playmaker_1  |   File "/usr/local/lib/python3.7/site-packages/gpapi/googleplay.py", line 223, in login
playmaker_1  |     raise SecurityCheckError()
playmaker_1  | gpapi.googleplay.SecurityCheckError
playmaker_1  | ERROR:tornado.access:500 POST /api/login (172.20.0.1) 505.10ms
```

**Comment by NoMore201** [comment]
Info about security check error: https://github.com/NoMore201/googleplay-api/issues/67#issuecomment-429523341

Usually to avoid this error you should enable 2-factor auth and have an app-specific password for playmaker, but recently the API started throwing that error even with the correct security settings

**Comment by NoMore201** [comment]
Since commit c3c9474 I put a link to the security check page in the login form: this link is enabled when SecurityCheckError is triggered by the server
