### ISSUE TITLE
Possible to make a public instance?

### ISSUE THREAD

**Issue by Nutomic** [NoMore201/playmaker#31]
Would it be possible to host a a public server with Playmaker, where users can pick which apps should be provided? Apparently now only the admin can add new apps, and also trigger updates or remove apps.

But if we could allow unregistered users to add apps (but not delete them), Playmaker could serve as a general purpose repo for all apps on Google Play. It would be a nice alternative to Yalp Store.

**Comment by corna** [comment]
The problem is that most of the apps on the Play Store are not redistributable, so we're not allowed to host an instance where anyone can add and download those apps. In the demo instance only some open-source redistributable apps are enabled.

**Comment by NoMore201** [comment]
Check #29 answer
