### ISSUE TITLE
Docker install not accessible from f-droid client.

### ISSUE THREAD

**Issue by LsPjvVzszDt** [NoMore201/playmaker#37]
I've installed the docker image and am running the following config:

> docker run  -d --name playmaker \
>     -p 5000:5000 \
>     -v /srv/fdroid:/data/fdroid \
>     -v /etc/letsencrypt/live/playmaker.example.com/cert.pem:/srv/cert.pem \
>     -v /etc/letsencrypt/live/playmaker.example.com/privkey.pem:/srv/privkey.pem \
>     -e HTTPS_CERTFILE="/srv/cert.pem" \
>     -e HTTPS_KEYFILE="/srv/privkey.pem" \
>     -e LANG_LOCALE="en_GB" \
>     -e LANG_TIMEZONE="Europe/London" \
>     nomore201/playmaker

I can access https://playmaker.example.com:5000/#!/ and have downloaded a dozen apps from the play store.

Updating the fdroid repo looks to be working OK in that I can see the apps and index files being updated.

The issue I'm seeing is that when I add the repo (URL https://playmaker.example.com:5000/fdroid)  to an f-droid client it is being reported as unsigned (I thought unsigned repo's are no longer supported). And when doing a repo update the client reports **error getting index file** for the repo.

Does someone know what needs to be done to resolve these issues?

Thanks

L

**Comment by mietzen** [comment]
I got the same Issue running the container on a Synology NAS

**Comment by Findus23** [comment]
Hi,
did you check https://github.com/NoMore201/playmaker/issues/32#issuecomment-403443248?
The URL should have a trailing slash (`/fdroid/`).

**Comment by LsPjvVzszDt** [comment]
Yes. I had already tested that.

If I put a trailing / in the Playmaker config it did not change the URL displayed on the Playmaker page. 

If I add the /  to the URL in F-Droid it drops it.

**Comment by slim8shady9** [comment]
Maybe your certificate is not trusted. You will always get that error unless your Android system trusts Playmaker's certificate.
Now you have three choices:
1. Use HTTP (if you are in a safe local network it's still acceptable)
2. Publish Playmaker's repo on Internet and buy a certificate (or use Let's Encrypt)
3. Force your self-signed certificate on your device system trusted certs ([this](https://blog.jeroenhd.nl/article/android-7-nougat-and-certificate-authorities) helped me a lot, tested 100%, root privileges needed)
The author should warn about this issue in the readme (IMHO).

**Comment by mietzen** [comment]
Thanks @slim8shady9 I'll try it tomorrow 👍

**Comment by LsPjvVzszDt** [comment]
My certs are fine and trusted.

**Comment by mietzen** [comment]
> Maybe your certificate is not trusted. You will always get that error unless your Android system trusts Playmaker's certificate.
> Now you have three choices:
> 
>     1. Use HTTP (if you are in a safe local network it's still acceptable)
> 
>     2. Publish Playmaker's repo on Internet and buy a certificate (or use Let's Encrypt)
> 
>     3. Force your self-signed certificate on your device system trusted certs ([this](https://blog.jeroenhd.nl/article/android-7-nougat-and-certificate-authorities) helped me a lot, tested 100%, root privileges needed)
>        The author should warn about this issue in the readme (IMHO).

For testing purposes I switched to http and it works 👍 
In the near future I'll try option 2 and/or 3

**Comment by LsPjvVzszDt** [comment]
I've just tested http and that worked.

I've just run some tests and can resolve this issue by using the Letsencrypt fullchain.pem  instead of  cert.pem so for the above example config the change is:

> -v /etc/letsencrypt/live/playmaker.example.com/cert.pem:/srv/cert.pem

to 

> -v /etc/letsencrypt/live/playmaker.example.com/fullchain.pem:/srv/cert.pem  \
