### ISSUE TITLE
Google Login doesn't retry on `UNKNOWN_ERR`

### ISSUE THREAD

**Issue by jbouter** [NoMore201/playmaker#46]
With a `credentials.conf` file present, playmaker should try and log in using these credentials. However, when the error `LoginError: 'server says: UNKNOWN_ERR'` is returned, playmaker stops trying to log in.

This error is however also thrown via the regular login interface in the webbrowser, and it can sometimes take up to 10 tries to properly login.

My proposed solution is to have playmaker attempt to login multiple times when an `UNKNOWN_ERR` is returned by Google. This value could either be hard-coded (say, 10 times), or be configurable in `credentials.conf`

**Comment by fellek** [comment]
Confirm. 
I am not able to login via credentials.conf or webui. 

using newest docker image and app specific password from google.

**Comment by jbouter** [comment]
Try pressing the login button multiple times. Seems like a very odd solution, but that does the trick for me. Just try until it logs you in (given you have verified your password is correct)

**Comment by fellek** [comment]
Thanks for reply. This solutions seems not to work for me. I am asked for security check (https://accounts.google.com/b/0/DisplayUnlockCaptcha) but not able to login. 

Playmaker gives me a tooltip "Wrong credentials" but Google registers Login with given Password.

**Comment by jbouter** [comment]
If you're using 2FA (Two Factor Authentication), be sure to create an app password specifically for playmaker within your Google security settings.

**Comment by Findus23** [comment]
Interestingly it stopped working for me too a few days ago. I didn't change anything, but login via the webui only get's a UNKNOWN_ERR with the app sepecific password and with trying multiple times.

Even accessing https://accounts.google.com/b/0/DisplayUnlockCaptcha via VPN from the IP address of the server doesn't help.

**Comment by Findus23** [comment]
Seems like we aren't the only ones: https://github.com/NoMore201/googleplay-api/issues/93

**Comment by zocker-160** [comment]
any updates on this? will playmaker even get updated? :thinking: :confused:

**Comment by mikken** [comment]
I still can't login with yoghi/playmaker fork.
I'm uising 2F-auth & newly created app password, tried both manual login and credentials.conf.
Message "Wrong credentials" pops up. Where do you check the detailed log?

Before reboot it was running so fine, a few months ago credentials.conf didn't work anyway, but it was accepting manual login.

**Comment by garrettboone** [comment]
@mikken I had the same experience but I commented out line 143 in config.py found in usr/local/lib/python3.7/site-packages/gpapi on the container. Restarted container, now works okay.

**Comment by jbouter** [comment]
I currently can't get out of the loop of `UNKNOWN_ERR`. But I suspect something has changed on Google's end. Has anyone had a successful login in the past three days?

**Comment by Cornul11** [comment]
As a hotfix, as seen [here](https://github.com/NoMore201/googleplay-api/issues/93#issuecomment-526366931), you have to comment out the 143rd line in config.py.

**Comment by garrettboone** [comment]
> 
> 
> I currently can't get out of the loop of `UNKNOWN_ERR`. But I suspect something has changed on Google's end. Has anyone had a successful login in the past three days?

Yes, active user. I also can restart the container, then log into a different account and pull down paid apps. Everything seems fine.

**Comment by yoghi** [comment]
Updated Pull Request.

**Comment by mikken** [comment]
After creating new account with veryfied phone number and removing mentioned lines from config.py (I thought yoghi fork already patched those, but seems not) I was able to login again.
I think creating new account wasn't necessary, but I'll leave it as it is.

**Comment by yoghi** [comment]
Update Pull Request

**Comment by davralin** [comment]
@yoghi Can you post your fork on docker hub? Seems nothing is going to happen here, so it looks like we should switch to something else.

**Comment by zocker-160** [comment]
@davralin you can just build a new docker image from @yoghi's repo:
`docker build https://github.com/yoghi/playmaker.git --tag=playmaker:yoghi`

**Comment by davralin** [comment]
I am aware. But if the image is uploaded to docker hub, I can use watchtower and it will be auto-updated for me whenever it is updated.

**Comment by zocker-160** [comment]
ok that is a fair point

**Comment by davralin** [comment]
@NoMore201 could you also push an update to docker-hub?

Perhaps even set up autobuild.
