### ISSUE TITLE
unstoppable relogin on search

### ISSUE THREAD

**Issue by dizzy666** [NoMore201/playmaker#7]
searching for 'phongit.quickreboot' produce unstoppable relogins.
```
Session tokens expired, re-login needed
Master token: ....
authSubToken: ...
Session tokens expired, re-login needed
```
after ~10 relogin:
```
Session tokens expired, re-login needed
Wrong credentials: 'server says: ServerError'
```
and after some more relogin a captcha request.

feature: counter to limit relogin per time or stop after wrong credentials ?

**Comment by NoMore201** [comment]
Since I implemented a fix for short-lived token in gpapi, I removed the relogin feature since is not necessary anymore, in commit 1273226. I still need to update image on Docker hub.

**Comment by dizzy666** [comment]
With latest git:
search for 'phongit.quickreboot' return search error and the container hang need restart to work again.
Logs shows: `Session tokens expired, re-login needed`
