### ISSUE TITLE
Missing result on search

### ISSUE THREAD

**Issue by dizzy666** [NoMore201/playmaker#8]
Searching `de.schildbach.oeffi` Result: App not listed
Searching `oeffi` Result: de.schildbach.oeffi is listed but `Version = 0`

On real device no problem to install. Perhaps wrong device or wrong country ?
Will try it later by api to hunt it down.

**Comment by NoMore201** [comment]
I have a similar problem with an app from an italian phone provider. I can search for it but can't download, and it returns `versionCode = 0`.
First I thought it could be a locale/timezone problem, so I manually set `it_IT` locale and `Europe/Rome` timezone to gpapi, but I can't download it anyway. I also tried to change strings in gpapi's `device.properties` file, also change device to gpapi, but same result. Can't really understand what's the problem.

**Comment by NoMore201** [comment]
Try again with latest dev version, the image is `nomore201/playmaker:dev.` As described in the README of the branch `dev` https://github.com/NoMore201/playmaker/blob/dev/README.md, you can provide locale and timezone to container with environment variables, so try to launch playmaker using your country locale and timezone.

**Comment by dizzy666** [comment]
Sorry for the delay in replying to.
With latest version all works fine.
