### ISSUE TITLE
Stop on Updating cache after restart

### ISSUE THREAD

**Issue by dizzy666** [NoMore201/playmaker#9]
Container hang on 'Updating cache' after installing com.textra.

To reproduce:
1. Use a empty repo (it also hang with not empty repo)
2. Install com.textra
3. Restart container
4. Check log no 'Added com.textra to cache' and Apps website show only 'Server is loading apks, please wait some seconds, then refresh'

**Comment by NoMore201** [comment]
Try latest commit, now playmaker is using a `ProcessPoolExecutor` to speedup cache building. Let me know if there is some improvements. I'm uploading new docker image right now.

**Comment by dizzy666** [comment]
Tried latest git commit. It still hang on 'Logging in and initializing apk cache' if i add com.textra and restart container.

**Comment by NoMore201** [comment]
Latest image ID is `7a624ec7198a`, check if you have it. Also, cache initialization can require lot of time if you have 10+ apks, I have reports of people waiting 20-30 minutes with lots of apps. When playmaker is updating, now it will poll the server every 5 seconds to check if it has completed initialization.

In order to be sure your instance is working as expected, during initialization check CPU and ram with `top` or `htop` and see if the process is parsing apk (usually it reaches 100% CPU on my machines), and report here

**Comment by dizzy666** [comment]
Have git `af68a0e`. Initialization works fine 233 apks (~2gb apk files) need ~3 minutes without com.textra app added. After adding com.textra it hang on 'Logging in and initializing apk cache' forever.

**Comment by NoMore201** [comment]
You're right, the library `pyaxmlparser` throws an error trying to parse that apk file. Here is the output
```
>>> from pyaxmlparser import APK
>>> a = APK('./com.textra.apk')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nomore/workspace/nogoogle/lib/python3.6/site-packages/pyaxmlparser/core.py", line 10, in __init__
    self.zip_file = get_zip_file(apk)
  File "/home/nomore/workspace/nogoogle/lib/python3.6/site-packages/pyaxmlparser/utils.py", line 29, in get_zip_file
    return ZipFile(resource)
  File "/usr/lib64/python3.6/zipfile.py", line 1108, in __init__
    self._RealGetContents()
  File "/usr/lib64/python3.6/zipfile.py", line 1175, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```
I'll add a try-catch in `get_details_from_apk`, and maybe we should forward the issue to `pyaxmlparser` repo

**Comment by NoMore201** [comment]
Issue reported here https://github.com/appknox/pyaxmlparser/issues/16
workaround added in abc009d
